// PSC (Product Service Code) and NAICS code → description lookups.
// SAM.gov v2 search API returns only the raw codes, not descriptions.
// These maps let us fill in the human-readable labels without extra API calls.

// ─── PSC Descriptions ─────────────────────────────────────────────────────────
// Keyed by the code exactly as stored (2-digit product groups, 1-letter service codes,
// and selected 4-character codes).  Lookup falls back from full code → 2-char prefix.
const PSC_MAP = {
  // Product groups (2-digit)
  '10': 'WEAPONS',
  '11': 'NUCLEAR ORDNANCE',
  '12': 'FIRE CONTROL EQUIPMENT',
  '13': 'AMMUNITION AND EXPLOSIVES',
  '14': 'GUIDED MISSILES',
  '15': 'AIRCRAFT AND AIRFRAME STRUCTURAL COMPONENTS',
  '16': 'AIRCRAFT COMPONENTS AND ACCESSORIES',
  '17': 'AIRCRAFT LAUNCHING, LANDING, AND GROUND HANDLING EQUIPMENT',
  '18': 'SPACE VEHICLES',
  '19': 'SHIPS, SMALL CRAFT, PONTOONS AND FLOATING DOCKS',
  '20': 'SHIP AND MARINE EQUIPMENT',
  '22': 'RAILWAY EQUIPMENT',
  '23': 'GROUND EFFECT VEHICLES, MOTOR VEHICLES, TRAILERS, AND CYCLES',
  '24': 'TRACTORS',
  '25': 'VEHICULAR EQUIPMENT COMPONENTS',
  '26': 'TIRES AND TUBES',
  '28': 'ENGINES, TURBINES, AND COMPONENTS',
  '29': 'ENGINE ACCESSORIES',
  '30': 'MECHANICAL POWER TRANSMISSION EQUIPMENT',
  '31': 'BEARINGS',
  '32': 'WOODWORKING MACHINERY AND EQUIPMENT',
  '34': 'METALWORKING MACHINERY',
  '35': 'SERVICE AND TRADE EQUIPMENT',
  '36': 'SPECIAL INDUSTRY MACHINERY',
  '37': 'AGRICULTURAL MACHINERY AND EQUIPMENT',
  '38': 'CONSTRUCTION, MINING, EXCAVATING, AND HIGHWAY MAINTENANCE EQUIPMENT',
  '39': 'MATERIALS HANDLING EQUIPMENT',
  '40': 'ROPE, CABLE, CHAIN, AND FITTINGS',
  '41': 'REFRIGERATING, AIR CONDITIONING, AND AIR CIRCULATING EQUIPMENT',
  '42': 'FIRE FIGHTING, RESCUE AND SAFETY EQUIPMENT AND ENVIRONMENTAL PROTECTION EQUIPMENT',
  '43': 'PUMPS AND COMPRESSORS',
  '44': 'FURNACE, STEAM PLANT, AND DRYING EQUIPMENT AND NUCLEAR REACTORS',
  '45': 'PLUMBING, HEATING, AND SANITATION EQUIPMENT',
  '46': 'WATER PURIFICATION AND SEWAGE TREATMENT EQUIPMENT',
  '47': 'PIPE, TUBING, HOSE, AND FITTINGS',
  '48': 'VALVES',
  '49': 'MAINTENANCE AND REPAIR SHOP EQUIPMENT',
  '51': 'HAND TOOLS',
  '52': 'MEASURING TOOLS',
  '53': 'HARDWARE AND ABRASIVES',
  '54': 'PREFABRICATED STRUCTURES AND SCAFFOLDING',
  '55': 'LUMBER, MILLWORK, PLYWOOD, AND VENEER',
  '56': 'CONSTRUCTION AND BUILDING MATERIALS',
  '57': 'WAREHOUSING AND STORAGE EQUIPMENT',
  '58': 'COMMUNICATION, DETECTION, AND COHERENT RADIATION EQUIPMENT',
  '59': 'ELECTRICAL AND ELECTRONIC EQUIPMENT COMPONENTS',
  '60': 'FIBER OPTIC MATERIALS, COMPONENTS, ASSEMBLIES, AND ACCESSORIES',
  '61': 'ELECTRIC WIRE AND POWER DISTRIBUTION EQUIPMENT',
  '62': 'LIGHTING EQUIPMENT AND LAMPS',
  '63': 'ALARM, SIGNAL, AND SECURITY DETECTION SYSTEMS',
  '65': 'MEDICAL, DENTAL, AND VETERINARY EQUIPMENT AND SUPPLIES',
  '66': 'INSTRUMENTS AND LABORATORY EQUIPMENT',
  '67': 'PHOTOGRAPHIC EQUIPMENT',
  '68': 'CHEMICALS AND CHEMICAL PRODUCTS',
  '69': 'TRAINING AIDS AND DEVICES',
  '70': 'INFORMATION TECHNOLOGY EQUIPMENT, SOFTWARE, SUPPLIES AND SUPPORT EQUIPMENT',
  '71': 'FURNITURE',
  '72': 'HOUSEHOLD AND COMMERCIAL FURNISHINGS AND APPLIANCES',
  '73': 'FOOD PREPARATION AND SERVING EQUIPMENT',
  '74': 'OFFICE MACHINES, TEXT PROCESSING SYSTEMS AND VISIBLE RECORD EQUIPMENT',
  '75': 'OFFICE SUPPLIES AND DEVICES',
  '76': 'BOOKS, MAPS, AND OTHER PUBLICATIONS',
  '77': 'MUSICAL INSTRUMENTS, PHONOGRAPHS, AND HOME-TYPE RADIOS',
  '78': 'RECREATIONAL AND ATHLETIC EQUIPMENT',
  '79': 'CLEANING EQUIPMENT AND SUPPLIES',
  '80': 'BRUSHES, PAINTS, SEALERS, AND ADHESIVES',
  '81': 'CONTAINERS, PACKAGING, AND PACKING SUPPLIES',
  '83': 'TEXTILES, LEATHER, FURS, APPAREL AND SHOE FINDINGS, TENTS AND FLAGS',
  '84': 'CLOTHING, INDIVIDUAL EQUIPMENT, AND INSIGNIA',
  '85': 'TOILETRIES',
  '87': 'AGRICULTURAL SUPPLIES',
  '88': 'LIVE ANIMALS',
  '89': 'SUBSISTENCE',
  '91': 'FUELS, LUBRICANTS, OILS AND WAXES',
  '93': 'NONMETALLIC FABRICATED MATERIALS',
  '94': 'NONMETALLIC CRUDE MATERIALS',
  '95': 'METAL BARS, SHEETS, AND SHAPES',
  '96': 'ORES, MINERALS, AND THEIR PRIMARY PRODUCTS',
  '99': 'MISCELLANEOUS',

  // Service codes (1-letter)
  'A': 'RESEARCH AND DEVELOPMENT',
  'B': 'SPECIAL STUDIES AND ANALYSES - NOT R&D',
  'C': 'ARCHITECT AND ENGINEERING SERVICES',
  'D': 'INFORMATION TECHNOLOGY AND TELECOMMUNICATIONS',
  'E': 'PURCHASE OF STRUCTURES AND FACILITIES',
  'F': 'NATURAL RESOURCES AND CONSERVATION SERVICES',
  'G': 'SOCIAL SERVICES',
  'H': 'QUALITY CONTROL, TESTING, AND INSPECTION SERVICES',
  'J': 'MAINTENANCE, REPAIR, AND REBUILDING OF EQUIPMENT',
  'K': 'MODIFICATION OF EQUIPMENT',
  'L': 'TECHNICAL REPRESENTATIVE SERVICES',
  'M': 'OPERATION OF GOVERNMENT-OWNED FACILITIES',
  'N': 'INSTALLATION OF EQUIPMENT',
  'P': 'SALVAGE SERVICES',
  'Q': 'MEDICAL SERVICES',
  'R': 'PROFESSIONAL, ADMINISTRATIVE, AND MANAGEMENT SUPPORT SERVICES',
  'S': 'UTILITIES AND HOUSEKEEPING SERVICES',
  'T': 'PHOTOGRAPHIC, MAPPING, PRINTING, AND PUBLICATIONS SERVICES',
  'U': 'EDUCATION AND TRAINING SERVICES',
  'V': 'TRANSPORTATION, TRAVEL, AND RELOCATION SERVICES',
  'W': 'LEASE OR RENTAL OF EQUIPMENT',
  'X': 'LEASE OR RENTAL OF FACILITIES',
  'Y': 'CONSTRUCTION OF STRUCTURES AND FACILITIES',
  'Z': 'MAINTENANCE, REPAIR, OR ALTERATION OF REAL PROPERTY',
};

// ─── NAICS Descriptions ───────────────────────────────────────────────────────
const NAICS_MAP = {
  // IT & Technology
  '511210': 'Software Publishers',
  '517110': 'Wired Telecommunications Carriers',
  '517210': 'Wireless Telecommunications Carriers (except Satellite)',
  '517410': 'Satellite Telecommunications',
  '517919': 'All Other Telecommunications',
  '518210': 'Data Processing, Hosting, and Related Services',
  '519130': 'Internet Publishing and Broadcasting and Web Search Portals',
  '541511': 'Custom Computer Programming Services',
  '541512': 'Computer Systems Design Services',
  '541513': 'Computer Facilities Management Services',
  '541519': 'Other Computer-Related Services',
  '541715': 'Research and Development in the Physical, Engineering, and Life Sciences',
  // Cybersecurity / Defense
  '541330': 'Engineering Services',
  '541611': 'Administrative Management and General Management Consulting Services',
  '541612': 'Human Resources Consulting Services',
  '541613': 'Marketing Consulting Services',
  '541614': 'Process, Physical Distribution, and Logistics Consulting Services',
  '541618': 'Other Management Consulting Services',
  '541690': 'Other Scientific and Technical Consulting Services',
  '541620': 'Environmental Consulting Services',
  '541990': 'All Other Professional, Scientific, and Technical Services',
  '561621': 'Security Systems Services (except Locksmiths)',
  '561612': 'Security Guards and Patrol Services',
  '561611': 'Investigation Services',
  // Construction
  '236220': 'Commercial and Institutional Building Construction',
  '237310': 'Highway, Street, and Bridge Construction',
  '237110': 'Water and Sewer Line and Related Structures Construction',
  '238210': 'Electrical Contractors and Other Wiring Installation Contractors',
  '238220': 'Plumbing, Heating, and Air-Conditioning Contractors',
  '238910': 'Site Preparation Contractors',
  '236210': 'Industrial Building Construction',
  '237120': 'Oil and Gas Pipeline and Related Structures Construction',
  '237130': 'Power and Communication Line and Related Structures Construction',
  '237210': 'Land Subdivision',
  '237990': 'Other Heavy and Civil Engineering Construction',
  '238110': 'Poured Concrete Foundation and Structure Contractors',
  '238120': 'Structural Steel and Precast Concrete Contractors',
  '238130': 'Framing Contractors',
  '238140': 'Masonry Contractors',
  '238150': 'Glass and Glazing Contractors',
  '238160': 'Roofing Contractors',
  '238170': 'Siding Contractors',
  '238190': 'Other Foundation, Structure, and Building Exterior Contractors',
  '238310': 'Drywall and Insulation Contractors',
  '238320': 'Painting and Wall Covering Contractors',
  '238330': 'Flooring Contractors',
  '238340': 'Tile and Terrazzo Contractors',
  '238350': 'Finish Carpentry Contractors',
  '238390': 'Other Building Finishing Contractors',
  '238990': 'All Other Specialty Trade Contractors',
  // Healthcare / Medical
  '621111': 'Offices of Physicians (except Mental Health Specialists)',
  '622110': 'General Medical and Surgical Hospitals',
  '621610': 'Home Health Care Services',
  '621999': 'All Other Miscellaneous Ambulatory Health Care Services',
  '325412': 'Pharmaceutical Preparation Manufacturing',
  '339112': 'Surgical and Medical Instrument Manufacturing',
  '339113': 'Surgical Appliance and Supplies Manufacturing',
  '621210': 'Offices of Dentists',
  '621310': 'Offices of Chiropractors',
  '621320': 'Offices of Optometrists',
  '621330': 'Offices of Mental Health Practitioners (except Physicians)',
  '621391': 'Offices of Podiatrists',
  '621399': 'Offices of All Other Health Practitioners',
  '621410': 'Family Planning Centers',
  '621420': 'Outpatient Mental Health and Substance Abuse Centers',
  '621491': 'HMO Medical Centers',
  '621492': 'Kidney Dialysis Centers',
  '621493': 'Freestanding Ambulatory Surgical and Emergency Centers',
  '621498': 'All Other Outpatient Care Centers',
  '621511': 'Medical Laboratories',
  '621512': 'Diagnostic Imaging Centers',
  '622210': 'Psychiatric and Substance Abuse Hospitals',
  '622310': 'Specialty (except Psychiatric and Substance Abuse) Hospitals',
  '623110': 'Nursing Care Facilities (Skilled Nursing Facilities)',
  '624110': 'Child and Youth Services',
  '624120': 'Services for the Elderly and Persons with Disabilities',
  // Logistics / Supply Chain
  '484110': 'General Freight Trucking, Local',
  '484121': 'General Freight Trucking, Long-Distance, Truckload',
  '484122': 'General Freight Trucking, Long-Distance, Less Than Truckload',
  '484210': 'Used Household and Office Goods Moving',
  '484220': 'Specialized Freight (except Used Goods) Trucking, Local',
  '484230': 'Specialized Freight (except Used Goods) Trucking, Long-Distance',
  '488510': 'Freight Transportation Arrangement',
  '493110': 'General Warehousing and Storage',
  '493120': 'Refrigerated Warehousing and Storage',
  '493130': 'Farm Product Warehousing and Storage',
  '493190': 'Other Warehousing and Storage',
  '561910': 'Packaging and Labeling Services',
  // Professional Services
  '561110': 'Office Administrative Services',
  '561210': 'Facilities Support Services',
  '561320': 'Temporary Help Services',
  '561330': 'Professional Employer Organizations',
  '561410': 'Document Preparation Services',
  '561421': 'Telephone Answering Services',
  '561422': 'Telemarketing Bureaus and Other Contact Centers',
  '561431': 'Private Mail Centers',
  '561439': 'Other Business Service Centers',
  '561440': 'Collection Agencies',
  '561450': 'Credit Bureaus',
  '561499': 'All Other Business Support Services',
  '561510': 'Travel Agencies',
  '561520': 'Tour Operators',
  '561710': 'Exterminating and Pest Control Services',
  '561720': 'Janitorial Services',
  '561730': 'Landscaping Services',
  '561740': 'Carpet and Upholstery Cleaning Services',
  '561790': 'Other Services to Buildings and Dwellings',
  '561920': 'Convention and Trade Show Organizers',
  '561990': 'All Other Support Services',
  // Education & Training
  '611110': 'Elementary and Secondary Schools',
  '611210': 'Junior Colleges',
  '611310': 'Colleges, Universities, and Professional Schools',
  '611410': 'Business and Secretarial Schools',
  '611420': 'Computer Training',
  '611430': 'Professional and Management Development Training',
  '611511': 'Cosmetology, Barber, Manicure, and Esthetics Schools',
  '611512': 'Flight Training',
  '611513': 'Apprenticeship Training',
  '611519': 'Other Technical and Trade Schools',
  '611620': 'Sports and Recreation Instruction',
  '611630': 'Language Schools',
  '611691': 'Exam Preparation and Tutoring',
  '611692': 'Automobile Driving Schools',
  '611699': 'All Other Miscellaneous Schools and Instruction',
  '611710': 'Educational Support Services',
  // Research & Development
  '541710': 'Physical, Engineering, and Life Sciences Research and Development',
  '541720': 'Social Sciences and Humanities Research and Development',
  '541380': 'Testing Laboratories',
  // Environmental
  '562910': 'Remediation Services',
  '562112': 'Hazardous Waste Collection',
  '562119': 'Other Waste Collection',
  '562211': 'Hazardous Waste Treatment and Disposal',
  '562219': 'Other Nonhazardous Waste Treatment and Disposal',
  '562920': 'Materials Recovery Facilities',
  '562991': 'Septic Tank and Related Services',
  '562998': 'All Other Miscellaneous Waste Management Services',
  // Defense / Aerospace
  '336411': 'Aircraft Manufacturing',
  '336412': 'Aircraft Engine and Engine Parts Manufacturing',
  '336413': 'Other Aircraft Parts and Equipment Manufacturing',
  '336992': 'Military Armored Vehicle, Tank, and Tank Component Manufacturing',
  '928110': 'National Security',
  '928120': 'International Affairs',
  // Primary Metal (331xxx)
  '331110': 'Iron and Steel Mills and Ferroalloy Manufacturing',
  '331210': 'Iron and Steel Pipe and Tube Manufacturing from Purchased Steel',
  '331221': 'Rolled Steel Shape Manufacturing',
  '331222': 'Steel Wire Drawing',
  '331313': 'Alumina Refining and Primary Aluminum Production',
  '331314': 'Secondary Smelting and Alloying of Aluminum',
  '331315': 'Aluminum Sheet, Plate, and Foil Manufacturing',
  '331316': 'Aluminum Extruded Product Manufacturing',
  '331318': 'Other Aluminum Rolling, Drawing, and Extruding',
  '331410': 'Nonferrous Metal (except Copper and Aluminum) Smelting and Refining',
  '331420': 'Copper Rolling, Drawing, Extruding and Alloying',
  '331491': 'Nonferrous Metal (except Copper and Aluminum) Rolling, Drawing, and Extruding',
  '331511': 'Iron Foundries',
  '331512': 'Steel Investment Foundries',
  '331513': 'Steel Foundries (except Investment)',
  '331523': 'Nonferrous Metal Die-Casting Foundries',
  '331524': 'Aluminum Foundries (except Die-Casting)',
  '331529': 'Other Nonferrous Foundries (except Die-Casting)',
  // Fabricated Metal (332xxx) — common in DLA/defense procurement
  '332111': 'Iron and Steel Forging',
  '332112': 'Nonferrous Forging',
  '332114': 'Custom Roll Forming',
  '332117': 'Powder Metallurgy Part Manufacturing',
  '332119': 'Metal Crown, Closure, and Other Metal Stamping (except Automotive)',
  '332211': 'Cutlery and Flatware (except Precious) Manufacturing',
  '332212': 'Hand and Edge Tool Manufacturing',
  '332213': 'Saw Blade and Handsaw Manufacturing',
  '332214': 'Kitchen Utensil, Pot, and Pan Manufacturing',
  '332311': 'Prefabricated Metal Building and Component Manufacturing',
  '332312': 'Fabricated Structural Metal Manufacturing',
  '332313': 'Plate Work Manufacturing',
  '332321': 'Metal Window and Door Manufacturing',
  '332322': 'Sheet Metal Work Manufacturing',
  '332323': 'Ornamental and Architectural Metal Work Manufacturing',
  '332410': 'Power Boiler and Heat Exchanger Manufacturing',
  '332420': 'Metal Tank (Heavy Gauge) Manufacturing',
  '332431': 'Metal Can Manufacturing',
  '332439': 'Other Metal Container Manufacturing',
  '332510': 'Hardware Manufacturing',
  '332613': 'Spring (Light Gauge) Manufacturing',
  '332618': 'Other Fabricated Wire Product Manufacturing',
  '332710': 'Machine Shops',
  '332721': 'Precision Turned Product Manufacturing',
  '332722': 'Bolt, Nut, Screw, Rivet, and Washer Manufacturing',
  '332811': 'Metal Heat Treating',
  '332812': 'Metal Coating, Engraving (except Jewelry and Silverware), and Allied Services',
  '332813': 'Electroplating, Polishing, Anodizing, and Coloring',
  '332911': 'Industrial Valve Manufacturing',
  '332912': 'Fluid Power Valve and Fittings Manufacturing',
  '332913': 'Plumbing Fixture Fitting and Trim Manufacturing',
  '332919': 'Other Metal Valve and Pipe Fitting Manufacturing',
  '332991': 'Ball and Roller Bearing Manufacturing',
  '332992': 'Small Arms Ammunition Manufacturing',
  '332993': 'Ammunition (except Small Arms) Manufacturing',
  '332994': 'Small Arms, Ordnance, and Ordnance Accessories Manufacturing',
  '332996': 'Fabricated Pipe and Fitting Manufacturing',
  '332999': 'All Other Miscellaneous Fabricated Metal Product Manufacturing',
  // Machinery (333xxx)
  '333120': 'Construction Machinery Manufacturing',
  '333131': 'Mining Machinery and Equipment Manufacturing',
  '333132': 'Oil and Gas Field Machinery and Equipment Manufacturing',
  '333241': 'Food Product Machinery Manufacturing',
  '333242': 'Semiconductor Machinery Manufacturing',
  '333249': 'Other Industrial Machinery Manufacturing',
  '333314': 'Optical Instrument and Lens Manufacturing',
  '333316': 'Photographic and Photocopying Equipment Manufacturing',
  '333413': 'Industrial and Commercial Fan and Blower and Air Purification Equipment Manufacturing',
  '333414': 'Heating Equipment (except Warm Air Furnaces) Manufacturing',
  '333415': 'Air-Conditioning and Warm Air Heating Equipment and Commercial Refrigeration Equipment Manufacturing',
  '333511': 'Industrial Mold Manufacturing',
  '333514': 'Special Die, Tool, Jig, and Fixture Manufacturing',
  '333515': 'Cutting Tool and Machine Tool Accessory Manufacturing',
  '333517': 'Machine Tool Manufacturing',
  '333611': 'Turbine and Turbine Generator Set Units Manufacturing',
  '333612': 'Speed Changer, Industrial High-Speed Drive, and Gear Manufacturing',
  '333613': 'Mechanical Power Transmission Equipment Manufacturing',
  '333618': 'Other Engine Equipment Manufacturing',
  '333911': 'Pump and Pumping Equipment Manufacturing',
  '333912': 'Air and Gas Compressor Manufacturing',
  '333921': 'Elevator and Moving Stairway Manufacturing',
  '333922': 'Conveyor and Conveying Equipment Manufacturing',
  '333923': 'Overhead Traveling Crane, Hoist, and Monorail System Manufacturing',
  '333991': 'Power-Driven Handtool Manufacturing',
  '333992': 'Welding and Soldering Equipment Manufacturing',
  '333993': 'Packaging Machinery Manufacturing',
  '333994': 'Industrial Process Furnace and Oven Manufacturing',
  '333995': 'Fluid Power Cylinder and Actuator Manufacturing',
  '333996': 'Fluid Power Pump and Motor Manufacturing',
  '333999': 'All Other General Purpose Machinery Manufacturing',
  // Computer and Electronic (334xxx)
  '334111': 'Electronic Computer Manufacturing',
  '334112': 'Computer Storage Device Manufacturing',
  '334118': 'Computer Terminal and Other Computer Peripheral Equipment Manufacturing',
  '334210': 'Telephone Apparatus Manufacturing',
  '334220': 'Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing',
  '334290': 'Other Communications Equipment Manufacturing',
  '334310': 'Audio and Video Equipment Manufacturing',
  '334413': 'Semiconductor and Related Device Manufacturing',
  '334417': 'Electronic Connector Manufacturing',
  '334418': 'Printed Circuit Assembly (Electronic Assembly) Manufacturing',
  '334419': 'Other Electronic Component Manufacturing',
  '334511': 'Search, Detection, Navigation, Guidance, Aeronautical Systems and Instruments Manufacturing',
  '334512': 'Automatic Environmental Control Manufacturing for Residential, Commercial, and Appliance Use',
  '334513': 'Instruments and Related Products Manufacturing for Measuring, Displaying, and Controlling Industrial Process Variables',
  '334514': 'Totalizing Fluid Meter and Counting Device Manufacturing',
  '334515': 'Instrument Manufacturing for Measuring and Testing Electricity and Electrical Signals',
  '334516': 'Analytical Laboratory Instrument Manufacturing',
  '334517': 'Irradiation Apparatus Manufacturing',
  '334519': 'Other Measuring and Controlling Device Manufacturing',
  // Transportation Equipment (336xxx)
  '336111': 'Automobile Manufacturing',
  '336112': 'Light Truck and Utility Vehicle Manufacturing',
  '336120': 'Heavy Duty Truck Manufacturing',
  '336211': 'Motor Vehicle Body Manufacturing',
  '336310': 'Motor Vehicle Gasoline Engine and Engine Parts Manufacturing',
  '336320': 'Motor Vehicle Electrical and Electronic Equipment Manufacturing',
  '336330': 'Motor Vehicle Steering and Suspension Components (except Springs) Manufacturing',
  '336340': 'Motor Vehicle Brake System Manufacturing',
  '336350': 'Motor Vehicle Transmission and Power Train Parts Manufacturing',
  '336360': 'Motor Vehicle Seating and Interior Trim Manufacturing',
  '336390': 'Other Motor Vehicle Parts Manufacturing',
  // Chemical Manufacturing (325xxx)
  '325110': 'Petrochemical Manufacturing',
  '325120': 'Industrial Gas Manufacturing',
  '325130': 'Synthetic Dye and Pigment Manufacturing',
  '325180': 'Other Basic Inorganic Chemical Manufacturing',
  '325199': 'All Other Basic Organic Chemical Manufacturing',
  '325211': 'Plastics Material and Resin Manufacturing',
  '325212': 'Synthetic Rubber Manufacturing',
  '325220': 'Artificial and Synthetic Fibers and Filaments Manufacturing',
  '325311': 'Nitrogenous Fertilizer Manufacturing',
  '325320': 'Pesticide and Other Agricultural Chemical Manufacturing',
  '325411': 'Medicinal and Botanical Manufacturing',
  '325413': 'In-Vitro Diagnostic Substance Manufacturing',
  '325414': 'Biological Product (except Diagnostic) Manufacturing',
  '325510': 'Paint and Coating Manufacturing',
  '325520': 'Adhesive Manufacturing',
  '325610': 'Soap and Other Detergent Manufacturing',
  '325620': 'Polish and Other Sanitation Good Manufacturing',
  '325910': 'Printing Ink Manufacturing',
  '325991': 'Custom Compounding of Purchased Resins',
  '325998': 'All Other Miscellaneous Chemical Product and Preparation Manufacturing',
  // Misc Manufacturing (339xxx)
  '339111': 'Laboratory Apparatus and Furniture Manufacturing',
  '339114': 'Dental Equipment and Supplies Manufacturing',
  '339115': 'Ophthalmic Goods Manufacturing',
  '339910': 'Jewelry and Silverware Manufacturing',
  '339920': 'Sporting and Athletic Goods Manufacturing',
  '339930': 'Doll, Toy, and Game Manufacturing',
  '339940': 'Office Supplies (except Paper) Manufacturing',
  '339950': 'Sign Manufacturing',
  '339991': 'Gasket, Packing, and Sealing Device Manufacturing',
  '339993': 'Fastener, Button, Needle, and Pin Manufacturing',
  '339994': 'Broom, Brush, Mop, and Sponge Manufacturing',
  '339999': 'All Other Miscellaneous Manufacturing',
};

// ─── Lookup helpers ────────────────────────────────────────────────────────────

export const getNaicsDescription = (code) => {
  if (!code) return '';
  const c = String(code).trim();
  return NAICS_MAP[c] || '';
};

export const getPscDescription = (code) => {
  if (!code) return '';
  const c = String(code).trim().toUpperCase();
  // Try exact match first, then 2-char prefix for multi-digit product codes
  return PSC_MAP[c] || PSC_MAP[c.slice(0, 2)] || PSC_MAP[c.slice(0, 1)] || '';
};
