import { useState, useRef } from 'react';
import { FileText, Sparkles, Copy, Download, CheckCircle, Loader2, Lock, RefreshCw, Building2, Target, Award, Users } from 'lucide-react';
import { aiAPI } from '../services/api';
import { useUserPlan } from '../hooks/useUserPlan';
import { AICreditsBar } from '../components/AICreditsBar';
import jsPDF from 'jspdf';

const CERTIFICATIONS = ['8(a)', 'WOSB', 'EDWOSB', 'HUBZone', 'SDVOSB', 'VOSB', 'SB', 'SDB', 'MBE', 'DBE'];

export default function CapabilityStatement() {
  const { plan: userPlan, loading: planLoading } = useUserPlan();
  const isPro = ['pro', 'enterprise'].includes(userPlan);

  const [form, setForm] = useState({
    certifications:    [],
    coreCompetencies:  '',
    pastPerformance:   '',
    differentiators:   '',
    targetAgency:      '',
    contactInfo:       '',
  });
  const [result,    setResult]    = useState('');
  const [loading,   setLoading]   = useState(false);
  const [error,     setError]     = useState('');
  const [copied,    setCopied]    = useState(false);
  const resultRef = useRef(null);

  const userName     = localStorage.getItem('userName')   || '';
  const businessName = localStorage.getItem('businessName') || userName;

  const toggleCert = (cert) => {
    setForm(f => ({
      ...f,
      certifications: f.certifications.includes(cert)
        ? f.certifications.filter(c => c !== cert)
        : [...f.certifications, cert],
    }));
  };

  const handleGenerate = async () => {
    setLoading(true);
    setError('');
    setResult('');
    try {
      const res = await aiAPI.capabilityStatement({
        ...form,
        certifications: form.certifications.join(', '),
      });
      setResult(res.data.data.statement);
      setTimeout(() => resultRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
    } catch (err) {
      const msg = err.response?.data?.message || 'Failed to generate. Please try again.';
      setError(msg);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(result);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const margin = 20;
    const pageW  = doc.internal.pageSize.getWidth();
    const maxW   = pageW - margin * 2;

    // Header bar
    doc.setFillColor(79, 70, 229);
    doc.rect(0, 0, pageW, 22, 'F');
    doc.setFontSize(14);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text(businessName || 'Company Name', margin, 14);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('CAPABILITY STATEMENT', pageW - margin, 14, { align: 'right' });

    // Body
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(result, maxW);
    let y = 32;
    lines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += 5.5;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by Sambid Notify — ${new Date().toLocaleDateString()}`, pageW / 2, 287, { align: 'center' });

    doc.save(`${(businessName || 'capability-statement').replace(/\s+/g, '-').toLowerCase()}-capability.pdf`);
  };

  if (planLoading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-indigo-500" />
      </div>
    );
  }

  if (!isPro) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center px-4">
        <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-10 max-w-md text-center">
          <div className="w-14 h-14 bg-indigo-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <Lock className="w-7 h-7 text-indigo-600" />
          </div>
          <h2 className="text-xl font-bold text-gray-900 mb-2">Pro Feature</h2>
          <p className="text-gray-500 mb-6">AI Capability Statement Generator is available on Pro ($79/mo) and Enterprise ($499/mo or $4,788/yr) plans.</p>
          <a href="/pricing" className="inline-flex items-center gap-2 px-6 py-3 bg-indigo-600 text-white rounded-xl font-semibold hover:bg-indigo-700 transition">
            Upgrade Now <Sparkles className="w-4 h-4" />
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-5 sm:py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <AICreditsBar feature="capability_statement" />
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center">
              <FileText className="w-5 h-5 text-white" />
            </div>
            <h1 className="text-2xl font-bold text-gray-900">AI Capability Statement Generator</h1>
          </div>
          <p className="text-gray-500 ml-13">Generate a professional, agency-ready capability statement in seconds using AI.</p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left — Input Form */}
          <div className="space-y-5">
            {/* Certifications */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
              <div className="flex items-center gap-2 mb-3">
                <Award className="w-4 h-4 text-indigo-500" />
                <h3 className="font-semibold text-gray-900 text-sm">Certifications</h3>
              </div>
              <div className="flex flex-wrap gap-2">
                {CERTIFICATIONS.map(c => (
                  <button
                    key={c}
                    onClick={() => toggleCert(c)}
                    className={`px-3 py-1 rounded-full text-xs font-medium border transition-all ${
                      form.certifications.includes(c)
                        ? 'bg-indigo-600 text-white border-indigo-600'
                        : 'bg-white text-gray-600 border-gray-300 hover:border-indigo-400'
                    }`}
                  >
                    {c}
                  </button>
                ))}
              </div>
            </div>

            {/* Core Competencies */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
              <div className="flex items-center gap-2 mb-2">
                <Target className="w-4 h-4 text-green-500" />
                <label className="font-semibold text-gray-900 text-sm">Core Competencies</label>
              </div>
              <textarea
                value={form.coreCompetencies}
                onChange={e => setForm(f => ({ ...f, coreCompetencies: e.target.value }))}
                rows={3}
                placeholder="e.g. Cybersecurity, Cloud Migration, Software Development, IT Support, Systems Integration..."
                className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400 resize-none"
              />
            </div>

            {/* Past Performance */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
              <div className="flex items-center gap-2 mb-2">
                <CheckCircle className="w-4 h-4 text-blue-500" />
                <label className="font-semibold text-gray-900 text-sm">Past Performance</label>
              </div>
              <textarea
                value={form.pastPerformance}
                onChange={e => setForm(f => ({ ...f, pastPerformance: e.target.value }))}
                rows={3}
                placeholder="e.g. Delivered $2M IT modernization project for DHS. Supported 500+ users at DoD facility for 3 years..."
                className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400 resize-none"
              />
            </div>

            {/* Differentiators */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
              <div className="flex items-center gap-2 mb-2">
                <Sparkles className="w-4 h-4 text-yellow-500" />
                <label className="font-semibold text-gray-900 text-sm">Why Choose Us / Differentiators</label>
              </div>
              <textarea
                value={form.differentiators}
                onChange={e => setForm(f => ({ ...f, differentiators: e.target.value }))}
                rows={2}
                placeholder="e.g. Certified team, 99.9% SLA, cleared personnel, agile delivery, 24/7 support..."
                className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400 resize-none"
              />
            </div>

            {/* Target Agency + Contact */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 space-y-4">
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <Building2 className="w-4 h-4 text-purple-500" />
                  <label className="font-semibold text-gray-900 text-sm">Target Agency (optional)</label>
                </div>
                <input
                  type="text"
                  value={form.targetAgency}
                  onChange={e => setForm(f => ({ ...f, targetAgency: e.target.value }))}
                  placeholder="e.g. Department of Defense, DHS, GSA, VA..."
                  className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400"
                />
              </div>
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <Users className="w-4 h-4 text-gray-400" />
                  <label className="font-semibold text-gray-900 text-sm">Contact Information</label>
                </div>
                <textarea
                  value={form.contactInfo}
                  onChange={e => setForm(f => ({ ...f, contactInfo: e.target.value }))}
                  rows={2}
                  placeholder="Name, Title, Phone, Email, Website, Address..."
                  className="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-400 resize-none"
                />
              </div>
            </div>

            {error && (
              <p className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-xl px-4 py-3">{error}</p>
            )}

            <button
              onClick={handleGenerate}
              disabled={loading}
              className="w-full flex items-center justify-center gap-2 py-3.5 bg-indigo-600 text-white rounded-xl font-semibold hover:bg-indigo-700 transition disabled:opacity-60"
            >
              {loading ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating...</> : <><Sparkles className="w-4 h-4" /> Generate Capability Statement</>}
            </button>
          </div>

          {/* Right — Result */}
          <div ref={resultRef}>
            {result ? (
              <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 sticky top-6">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="font-semibold text-gray-900">Generated Statement</h3>
                  <div className="flex gap-2">
                    <button
                      onClick={handleGenerate}
                      title="Regenerate"
                      className="p-2 text-gray-500 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition"
                    >
                      <RefreshCw className="w-4 h-4" />
                    </button>
                    <button
                      onClick={handleCopy}
                      className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium border border-gray-200 rounded-lg hover:bg-gray-50 transition"
                    >
                      {copied ? <><CheckCircle className="w-3.5 h-3.5 text-green-500" /> Copied!</> : <><Copy className="w-3.5 h-3.5" /> Copy</>}
                    </button>
                    <button
                      onClick={handleDownloadPDF}
                      className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition"
                    >
                      <Download className="w-3.5 h-3.5" /> PDF
                    </button>
                  </div>
                </div>
                <div className="prose prose-sm max-w-none">
                  <pre className="whitespace-pre-wrap font-sans text-sm text-gray-700 leading-relaxed bg-gray-50 rounded-xl p-4 border border-gray-100 max-h-[600px] overflow-y-auto">
                    {result}
                  </pre>
                </div>
              </div>
            ) : (
              <div className="bg-white rounded-2xl border-2 border-dashed border-gray-200 p-10 text-center flex flex-col items-center justify-center min-h-[400px]">
                <FileText className="w-12 h-12 text-gray-300 mb-3" />
                <p className="text-gray-400 font-medium">Your capability statement will appear here</p>
                <p className="text-gray-300 text-sm mt-1">Fill in the form and click Generate</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
